version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: time-dun-flights-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=time-dun-flights
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: time-dun-flights-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/time-dun-flights
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
